/**
 * scripts/generate.ts
 *
 * SINGLE ENTRY POINT — run whenever:
 *   - The Postman collection updates
 *   - The commercetools SDK updates
 *
 *   npx ts-node scripts/generate.ts
 *   # or: npm run generate
 *
 * What it does:
 *
 *   STEP 1 — Postman collection → operation properties
 *       Generates:
 *         nodes/Commercetools/generated/properties.ts
 *         nodes/Commercetools/generated/operations.json
 *
 *   STEP 2 — SDK .d.ts → event registry
 *       Generates:
 *         nodes/Commercetools/generated/ctp-event-registry.json
 *
 *   STEP 3 — Event registry → subscription.properties.ts
 *       Generates:
 *         nodes/Commercetools/generated/subscription.properties.ts
 *
 * After running: npm run build
 */

import * as fs from 'fs';
import * as path from 'path';
import * as https from 'https';

import { parseCollection } from './parseCollection';
import { generateAllNodeProperties } from './generateProperties';

import { generateCtpEventRegistry } from './generateCtpRegistry';
import { generateSubscriptionProperties } from './generateSubscriptionProperties';

// ─────────────────────────────────────────────────────────────────────────────
// Configuration
// ─────────────────────────────────────────────────────────────────────────────

const COLLECTION_URL =
	'https://raw.githubusercontent.com/commercetools/commercetools-postman-collection/master/api/collection.json';

const COLLECTION_LOCAL_PATH = path.resolve(__dirname, '../collection.json');

const OUTPUT_DIR = path.resolve(__dirname, '../nodes/Commercetools/generated');

const FOLDERS_TO_GENERATE = ['Products', 'Customers', 'Carts', 'Orders'];

const RESOURCES_TO_GENERATE = ['product', 'customer', 'cart', 'order'];
// ─────────────────────────────────────────────────────────────────────────────
// Download helper
// ─────────────────────────────────────────────────────────────────────────────

function downloadFile(url: string, dest: string): Promise<void> {
	return new Promise((resolve, reject) => {
		const file = fs.createWriteStream(dest);

		https
			.get(url, (response) => {
				if (response.statusCode === 301 || response.statusCode === 302) {
					file.close();
					downloadFile(response.headers.location!, dest).then(resolve).catch(reject);
					return;
				}

				response.pipe(file);
				file.on('finish', () => file.close(() => resolve()));
			})
			.on('error', (err) => {
				fs.unlink(dest, () => {});
				reject(err);
			});
	});
}

// ─────────────────────────────────────────────────────────────────────────────
// STEP 1 — Postman → Node operation properties
// ─────────────────────────────────────────────────────────────────────────────

async function generateFromCollection(): Promise<void> {
	banner('STEP 1 — Postman Collection → Operation Properties');

	console.info('  🔄  Downloading latest Postman collection...');
	try {
		await downloadFile(COLLECTION_URL, COLLECTION_LOCAL_PATH);
		console.info(`  ✅  Saved to ${COLLECTION_LOCAL_PATH}`);
	} catch {
		if (fs.existsSync(COLLECTION_LOCAL_PATH)) {
			console.warn('  ⚠️   Download failed — using cached collection.json');
		} else {
			throw new Error('No network and no local collection.json found.');
		}
	}

	// eslint-disable-next-line @typescript-eslint/no-require-imports
	const collection = require(COLLECTION_LOCAL_PATH);

	console.info(`  📦  Parsing folders: ${FOLDERS_TO_GENERATE.join(', ')}`);
	const operations = parseCollection(collection, FOLDERS_TO_GENERATE);

	console.info(`  ✅  Found ${operations.length} operations`);

	const nodeProperties = generateAllNodeProperties(operations, FOLDERS_TO_GENERATE);

	console.info(`  ✅  Generated ${nodeProperties.length} property definitions`);

	fs.mkdirSync(OUTPUT_DIR, { recursive: true });

	const propertiesTs = `/**
 * AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
 * Generated by: scripts/generate.ts
 * Source: ${COLLECTION_URL}
 * Generated at: ${new Date().toISOString()}
 */

import type { INodeProperties } from 'n8n-workflow';

export const generatedProperties: INodeProperties[] = ${JSON.stringify(nodeProperties, null, 2)};
`;

	fs.writeFileSync(path.join(OUTPUT_DIR, 'properties.ts'), propertiesTs);

	const opsMap: Record<string, unknown> = {};
	for (const op of operations) opsMap[op.value] = op;

	fs.writeFileSync(path.join(OUTPUT_DIR, 'operations.json'), JSON.stringify(opsMap, null, 2));

	console.info('  ✅  Wrote operation property files');
}

// ─────────────────────────────────────────────────────────────────────────────
// STEP 2 — SDK → Registry JSON
// ─────────────────────────────────────────────────────────────────────────────

function generateRegistry(): void {
	banner('STEP 2 — SDK .d.ts → Event Registry');

	generateCtpEventRegistry(OUTPUT_DIR, {allowedResources: RESOURCES_TO_GENERATE});

	console.info('  ✅  Event registry generated');
}

// ─────────────────────────────────────────────────────────────────────────────
// STEP 3 — Registry → subscription.properties.ts
// ─────────────────────────────────────────────────────────────────────────────

function generateSubscriptions(): void {
	banner('STEP 3 — Event Registry → Subscription Properties');

	generateSubscriptionProperties();

	console.info('  ✅  Subscription properties generated');
}

// ─────────────────────────────────────────────────────────────────────────────
// Utilities
// ─────────────────────────────────────────────────────────────────────────────

function banner(title: string): void {
	const line = '━'.repeat(60);
	console.info(`\n${line}`);
	console.info(`  ${title}`);
	console.info(line);
}

// ─────────────────────────────────────────────────────────────────────────────
// Entry point
// ─────────────────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
	console.info('\n🚀  commercetools n8n node — unified generator');
	console.info(`    ${new Date().toISOString()}`);

	try {
		await generateFromCollection();
		generateRegistry();
		generateSubscriptions();
	} catch (err) {
		console.error('\n❌  Generation failed:', err);
		process.exit(1);
	}

	banner('🎉  All done! Now run: npm run build');
}

main().catch((err) => {
	console.error('❌  Fatal error:', err);
	process.exit(1);
});
