/**
 * scripts/generate.ts
 *
 * SINGLE ENTRY POINT — run whenever the Postman collection or CT SDK updates:
 *
 *   npx ts-node scripts/generate.ts
 *   # or: npm run generate
 *
 * What it does:
 *   Step 1 — Downloads the latest commercetools Postman collection, parses
 *             configured resource folders, and writes:
 *               nodes/Commercetools/generated/properties.ts
 *               nodes/Commercetools/generated/operations.json
 *
 *   Step 2 — Reads @commercetools/platform-sdk .d.ts files and writes:
 *               nodes/Commercetools/properties/subscription.properties.ts
 *
 * After running: npm run build
 *
 * Individual generators can also be run standalone:
 *   npx ts-node scripts/generateSubscriptionProperties.ts
 */

import * as fs from 'fs';
import * as path from 'path';
import * as https from 'https';

import { parseCollection } from './parseCollection';
import { generateAllNodeProperties } from './generateProperties';
import { generateSubscriptionProperties, SUBSCRIPTION_PROPERTIES_PATH, RESOURCES_TO_GENERATE } from './generateSubscriptionProperties';

// ─── Configuration ────────────────────────────────────────────────────────────

const COLLECTION_URL =
    'https://raw.githubusercontent.com/commercetools/commercetools-postman-collection/master/api/collection.json';

const COLLECTION_LOCAL_PATH = path.resolve(__dirname, '../collection.json');

const OUTPUT_DIR = path.resolve(__dirname, '../nodes/Commercetools/generated');

/**
 * Folder names must exactly match the Postman collection folder names.
 * Add/remove entries here to include/exclude resources from the node.
 */
const FOLDERS_TO_GENERATE = [
    'Products',
    'Customers',
];

// ─── Download helper ──────────────────────────────────────────────────────────

function downloadFile(url: string, dest: string): Promise<void> {
    return new Promise((resolve, reject) => {
        const file = fs.createWriteStream(dest);
        https.get(url, (response) => {
            // Follow redirects
            if (response.statusCode === 301 || response.statusCode === 302) {
                file.close();
                downloadFile(response.headers.location!, dest).then(resolve).catch(reject);
                return;
            }
            response.pipe(file);
            file.on('finish', () => file.close(() => resolve()));
        }).on('error', (err) => {
            fs.unlink(dest, () => { });
            reject(err);
        });
    });
}

// ─── Step 1: Postman collection → operation properties ───────────────────────

async function generateFromCollection(): Promise<void> {
    banner('STEP 1 — Postman Collection → Operation Properties');

    // Download with local cache fallback
    console.log('  🔄  Downloading latest Postman collection...');
    try {
        await downloadFile(COLLECTION_URL, COLLECTION_LOCAL_PATH);
        console.log(`  ✅  Saved to ${COLLECTION_LOCAL_PATH}`);
    } catch {
        if (fs.existsSync(COLLECTION_LOCAL_PATH)) {
            console.warn('  ⚠️   Download failed — using cached collection.json');
        } else {
            throw new Error('No network and no local collection.json found.');
        }
    }

    // Parse
    console.log(`  📦  Parsing folders: ${FOLDERS_TO_GENERATE.join(', ')}`);
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const collection = require(COLLECTION_LOCAL_PATH);
    const operations = parseCollection(collection, FOLDERS_TO_GENERATE);
    console.log(`  ✅  Found ${operations.length} operations`);

    const nodeProperties = generateAllNodeProperties(operations, FOLDERS_TO_GENERATE);
    console.log(`  ✅  Generated ${nodeProperties.length} property definitions`);

    // Write outputs
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });

    // properties.ts — imported by the node at TypeScript build time
    const propertiesTs = `/**
 * AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
 * Generated by: scripts/generate.ts
 * Source: ${COLLECTION_URL}
 * Generated at: ${new Date().toISOString()}
 *
 * Regenerate: npm run generate
 */

import type { INodeProperties } from 'n8n-workflow';

export const generatedProperties: INodeProperties[] = ${JSON.stringify(nodeProperties, null, 2)};
`;
    fs.writeFileSync(path.join(OUTPUT_DIR, 'properties.ts'), propertiesTs);
    console.log('  ✅  Wrote nodes/Commercetools/generated/properties.ts');

    // operations.json — runtime lookup: operationValue → ParsedOperation
    const opsMap: Record<string, unknown> = {};
    for (const op of operations) opsMap[op.value] = op;
    fs.writeFileSync(
        path.join(OUTPUT_DIR, 'operations.json'),
        JSON.stringify(opsMap, null, 2),
    );
    console.log('  ✅  Wrote nodes/Commercetools/generated/operations.json');

    // Summary
    console.log('\n  📋  Operations by folder:');
    for (const folder of FOLDERS_TO_GENERATE) {
        const names = operations
            .filter(o => o.folder === folder && !o.isUpdateAction)
            .map(o => o.name);
        console.log(`      ${folder}: ${names.join(', ')}`);
    }
}

// ─── Step 2: SDK .d.ts → subscription.properties.ts ─────────────────────────

function runSubscriptionGenerator(): void {
    banner('STEP 2 — SDK .d.ts → Subscription Properties');
    // Delegate entirely to the dedicated module — no logic duplicated here.
    // RESOURCES_TO_GENERATE is the filter; edit it in generateSubscriptionProperties.ts.
    generateSubscriptionProperties(SUBSCRIPTION_PROPERTIES_PATH, RESOURCES_TO_GENERATE);
}

// ─── Utilities ────────────────────────────────────────────────────────────────

function banner(title: string): void {
    const line = '━'.repeat(56);
    console.log(`\n${line}`);
    console.log(`  ${title}`);
    console.log(line);
}

// ─── Entry point ──────────────────────────────────────────────────────────────

async function main(): Promise<void> {
    console.log('\n🚀  commercetools n8n node — property generator');
    console.log(`    ${new Date().toISOString()}`);

    try {
        await generateFromCollection();
    } catch (err) {
        console.error('\n❌  Collection generation failed:', err);
        process.exit(1);
    }

    try {
        runSubscriptionGenerator();
    } catch (err) {
        console.error('\n❌  Subscription generation failed:', err);
        process.exit(1);
    }

    banner('🎉  All done! Now run: npm run build');
    console.log();
}

main().catch(err => {
    console.error('❌  Fatal error:', err);
    process.exit(1);
});